version: '3'

services:
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - moneyapp
    volumes:
      - ./:/var/www/html
      - ./logs/nginx:/var/log/nginx
  php:
    image: php:fpm-alpine
    networks:
      - moneyapp
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log


networks:
  moneyapp:
    driver: bridge